Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.provider "virtualbox" do |v|   
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  config.vm.provision "shell",
  inline: "apt update "

  config.vm.provision "shell",
  inline: "apt install nginx -y "
end