Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-22.04"  
  config.vm.provision "shell",  inline: "apt update"
  config.vm.provision "shell",  inline: "apt install ansible -y"
  
  config.vm.provider "virtualbox" do |v|    
    v.memory = 1024
    v.cpus = 2      
  end
end