
Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/focal64"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "public_network"

  # config.vm.provision "shell",
  #  inline: "apt update"

   # config.vm.provision "shell",
   # inline: "apt install nginx -y"

   # config.vm.provision "shell",
   # inline: "apt install net-tools -y"

    #config.vm.provision "shell",
    #inline: "cp -rf /vagrant/site/* /var/www/html/"

    config.vm.synced_folder "E:\\COS\\Git\\ComputacaoOrientadaServicos\\Aula02\\site", "/var/www/html"
        
end
