
Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-22.04"

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.network "forwarded_port", guest: 80, host: 8080
    # config.vm.network "public_network"    
    config.vm.provision "shell", inline: "apt update"    
    config.vm.provision "shell", inline: "apt install nginx -y"
    config.vm.provision "shell", inline: "apt install net-tools -y"
    # config.vm.provision "shell", inline: "cp -rf /vagrant/site/* /var/www/html/"   
    # config.vm.synced_folder "./site", "/var/www/html"


        
end
