Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-22.04"
  
  config.vm.provision "shell",  inline: "apt update"
  
  config.vm.define "web" do |web|
    web.vm.provision "shell",  inline: "apt install nginx -y"  
    web.vm.provider "virtualbox" do |v|
      v.name = "server_web"
      v.memory = 250
      v.cpus = 2      
    end  
  end

  config.vm.define "db" do |db|
    db.vm.provision "shell",  inline: "apt install mysql-server -y"  
    db.vm.provider "virtualbox" do |v|
      v.name = "server_db"
      v.memory = 800
      v.cpus = 2
    end
  end
end